server:
  port: 8080

spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/ewm_db
    username: dbuser
    password: 12345

logging:
  level:
    com.fasterxml.jackson: DEBUG
    org.springframework.web: DEBUG
