grpc:
  server:
    port: 0

server:
  port: 0

spring:
  kafka:
    producer:
      bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: ru.practicum.collector.config.BaseAvroSerializer
