# H2
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.url=jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
spring.datasource.username=sa
spring.datasource.password=

# schema
spring.jpa.hibernate.ddl-auto=create-drop

# console H2
spring.h2.console.enabled=true

# log
logging.level.ru.practicum=DEBUG
logging.level.org.springframework.validation=TRACE
logging.level.org.hibernate=DEBUG
