
{
  "type": "record",
  "namespace": "ru.practicum.ewm.stats.avro",
  "name": "UserActionAvro",
  "fields": [
    { "name": "userId", "type": "long" },
    { "name": "eventId", "type": "long" },
    {
      "name": "actionType",
      "type": {
        "type": "enum",
        "namespace": "ru.practicum.ewm.stats.avro",
        "name": "ActionTypeAvro",
        "symbols": ["VIEW", "REGISTER", "LIKE"]
      }
    },
    { "name": "timestamp", "type": { "type": "long", "logicalType": "timestamp-millis" } }
  ]
}
