server:
  port: 0

grpc:
  server:
    port: -1
  client:
    collector:
      address: discovery:///collector
      negotiation-type: plaintext
    analyzer:
      address: discovery:///analyzer
      negotiation-type: plaintext

spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5434/event_db
    username: dbuser
    password: 12345

logging:
  level:
    com.fasterxml.jackson: DEBUG
    org.springframework.web: DEBUG
