server:
  port: 8080

spring:
  application:
    name: main-service
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always
  main:
    allow-bean-definition-overriding: false
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/ewm_db
    username: dbuser
    password: 12345

logging:
  level:
    com.fasterxml.jackson: DEBUG
    org.springframework.web: DEBUG

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
